### PR TITLE
style :  optimized code & UI

### PR DESCRIPTION
**Pull request by ZeeshanMukhtar1**
## Description

This PR refines the user interface and functionality of the SheSharp React.js web application. The following improvements have been implemented:

- **UI Enhancements:** The user interface has been updated to provide a more modern and visually appealing look. The changes include a redesigned card layout and an attractive title to create a visually engaging experience for users.

- **Table Styling:** The data display table has been styled for better readability. Thicker lines have been added between table cells to provide clear separation.

- **Comments and Documentation:** Comments within the code have been improved for clarity and maintainability. Additionally, a descriptive punchline title has been added to the card for an engaging user experience.

- **Improved Fetching:** The Fetch API has been integrated to fetch data from a public API (JSONPlaceholder) when the "Fetch Data" button is clicked. This provides users with the ability to experience data retrieval in real-time, enhancing the application's interactivity.

These enhancements collectively create a more engaging and user-friendly experience, making the SheSharp React.js application more modern and user-centered. The changes aim to elevate the overall usability and aesthetic of the application.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @ZeeshanMukhtar1 , thanks for your interest in contributing. Currently we are focusing on assigning issues and accepting PRs from our community members and underrepresented genders. You can learn more about our organization on the [SheSharp Website.](https://www.shesharp.co)

**Comment by ghost** [comment]
@ZeeshanMukhtar1 Thanks again for your interest. One thing is that we want to keep this repo true to the original design - which is not fetching from a public API, but using JSON.

We have assigned the header and footer issues to other community members. Would you be open to contributing a specific component for the UI or something else?

I don't want to totally shoot down your PR, I'm sorry for that. We are still figuring out how to best focus our efforts on our community members / underrepresented genders, but it's a process. We are open to contributions from others, if you have insight or suggestions to make it more collaborative we would love to hear from you.

If you want to continue the discussion, I invite you to join our [Slack](https://www.shesharp.co/slack). We have an #open-source channel as well as a #devs channel.

**Comment by ZeeshanMukhtar1** [comment]
@mariahlaqua Thank you for your response and clarification. I appreciate your commitment to maintaining the original design. I'm open to contributing in any way that aligns with your project's goals. If you have specific suggestions or tasks, please let me know. I'm here to help and support your efforts to make the project more collaborative.

**Comment by ghost** [comment]
Thank you for understanding @ZeeshanMukhtar1 , we're thinking on it today and I'll get back to you. 👍 Super appreciate your patience!

**Pull request closed without merging**
